# Generated by Django 5.1.3 on 2024-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=225)),
                ('logo', models.ImageField(default='default.jpg', upload_to='images/')),
                ('about', models.TextField()),
                ('founded_at', models.PositiveIntegerField()),
                ('country_of_origin', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
