# Generated by Django 5.1.2 on 2024-11-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
                ('logo', models.FileField(upload_to='images/')),
                ('about', models.TextField()),
                ('found_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
