# Generated by Django 5.1.3 on 2024-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='images/default.jpg', upload_to='images/brands/')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('headquarters', models.CharField(max_length=1024)),
                ('founder', models.CharField(max_length=256)),
                ('founded', models.DateField()),
            ],
        ),
    ]
