# Generated by Django 5.1.2 on 2024-11-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='found_at',
            field=models.DateField(),
        ),
    ]
