# Generated by Django 5.1.3 on 2024-11-22 17:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='images/default.jpg', storage=django.core.files.storage.FileSystemStorage(location='/media/images/brands'), upload_to=''),
        ),
    ]
