# Generated by Django 5.1.3 on 2024-11-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='founded_at',
        ),
    ]
