# Generated by Django 5.1.1 on 2024-11-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='brand_logo/default.jpg', upload_to='brand_logo/'),
        ),
    ]
