# Generated by Django 5.1.3 on 2024-11-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_remove_brand_founded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='found_at',
            field=models.DateField(null=True),
        ),
    ]
