# Generated by Django 5.1.3 on 2024-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_headquarters_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='founded_at',
            field=models.IntegerField(),
        ),
    ]
