# Generated by Django 5.1.2 on 2024-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_alter_car_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='colors',
            new_name='color_ids',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='model_year',
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
