# Generated by Django 5.1.2 on 2024-11-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_rename_brand_car_brand_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='color_ids',
            new_name='color',
        ),
    ]
