# Generated by Django 5.1.3 on 2024-11-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0001_initial'),
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brands_app.brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
