# Generated by Django 5.0.7 on 2024-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')]),
        ),
    ]
