# Generated by Django 5.0.7 on 2024-07-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
    ]
