# Generated by Django 5.0.7 on 2024-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='esrb',
            field=models.CharField(choices=[('E', 'Everyone'), ('E10', 'Everyone +10'), ('T', 'Teen'), ('M', 'Mature 17+'), ('AO', 'Adult Only 18+'), ('RP', 'Rating Pending')], default='RP', max_length=64),
        ),
    ]
