# Generated by Django 5.1.3 on 2024-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(upload_to="images/avatars/"),
        ),
    ]
