# Generated by Django 5.1.3 on 2024-11-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="images/avatars/avatar.webp", upload_to="images/avatars/"
            ),
        ),
    ]
