# Generated by Django 5.1.2 on 2024-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('about', models.TextField(blank=True)),
                ('founded_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
