# Generated by Django 5.1.2 on 2024-11-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0002_brand_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('BMW', 'BMW'), ('MAZDA', 'Mazda'), ('TOYOTA', 'Toyota'), ('MERCEDES', 'Mercedes'), ('JEEP', 'Jeep'), ('FORD', 'Ford'), ('DODGE', 'Dodge')], default='BMW', max_length=20),
        ),
    ]
