# Generated by Django 5.1.2 on 2024-11-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0003_alter_brand_brand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
