# Generated by Django 5.1.3 on 2024-11-21 14:32

import django.core.validators
from django.db import migrations, models

def populate_colors(apps, schema_editor):
    Color = apps.get_model('cars', 'Color')

    predefined_colors = [
        {"name": "Red", "hex_code": "#FF0000"},
        {"name": "Blue", "hex_code": "#0000FF"},
        {"name": "Green", "hex_code": "#00FF00"},
        {"name": "Black", "hex_code": "#000000"},
        {"name": "White", "hex_code": "#FFFFFF"},
    ]

    for color_data in predefined_colors:
        Color.objects.get_or_create(name=color_data["name"], hex_code=color_data["hex_code"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='colors/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=1024)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2100)])),
                ('engine', models.CharField(max_length=255)),
                ('power', models.PositiveIntegerField(help_text='Power in horsepower (HP)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Pre-order', 'Pre-order')], max_length=50)),
                ('speed', models.PositiveIntegerField(help_text='Top speed in km/h or mph')),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan')], max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_colors', models.ManyToManyField(related_name='cars', to='cars.color')),
            ],
        ),
        migrations.RunPython(populate_colors),  

    ]
