# Generated by Django 5.1.3 on 2024-11-21 05:39

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_remove_brand_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hexadeicml_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='images/')),
                ('specs', models.TextField()),
                ('model', models.CharField(max_length=255)),
                ('segment', models.CharField(choices=[('economy', 'Economy'), ('luxury', 'Luxury'), ('sports', 'Sports'), ('electric', 'Electric'), ('sedan', 'Sedan'), ('wagon', 'Wagon'), ('premium', 'Premium'), ('suv', 'Sport Utility Vehicle'), ('minivan', 'Minivan')], max_length=64)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
    ]
