# Generated by Django 5.1.3 on 2024-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cargoSpace',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.photo'),
        ),
    ]
