# Generated by Django 5.1.2 on 2024-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=models.CharField(default='#4335A7', max_length=7),
        ),
    ]
