# Generated by Django 5.1.3 on 2024-11-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(to='cars.color'),
        ),
    ]
