# Generated by Django 5.1.3 on 2024-11-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_color_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="color", name="hex_code",),
    ]
