# Generated by Django 5.1.3 on 2024-11-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_engine_car_topspeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
    ]
