# Generated by Django 5.1.3 on 2024-11-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_cargospace_alter_car_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='cargoSpace',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.ManyToManyField(to='cars.color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='infotainment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='performance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='cars_photos/%Y/%m/%d/'),
        ),
    ]
