# Generated by Django 5.1.3 on 2024-11-21 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_remove_brand_founded_at'),
        ('cars', '0003_remove_car_created_at_remove_car_photos_photo_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cargoSpace',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.ManyToManyField(blank=True, to='cars.color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='infotainment',
            field=models.CharField(default='Basic', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='performance',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
        ),
    ]
