# Generated by Django 5.1.3 on 2024-11-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="available_colors",
            field=models.ManyToManyField(
                blank=True, related_name="cars", to="cars.color"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="brands.Brand",
            ),
        ),
    ]
