# Generated by Django 5.1.3 on 2024-11-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_currency_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=15),
        ),
    ]
