# Generated by Django 5.1.3 on 2024-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_color_hex_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="color", name="photo",),
        migrations.AddField(
            model_name="color",
            name="color_photo",
            field=models.ImageField(
                default="photos/default_color.jpg", upload_to="photos/"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
