# Generated by Django 5.1.3 on 2024-11-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_created_at_alter_car_brand_alter_car_cargospace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
            preserve_default=False,
        ),
    ]
