# Generated by Django 5.1.3 on 2024-11-21 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
