# Generated by Django 5.1.3 on 2024-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_remove_color_photo_color_color_photo_alter_car_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="color", name="color_photo",),
        migrations.AddField(
            model_name="color",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
