# Generated by Django 5.1.3 on 2024-11-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_addedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexCode',
            field=models.CharField(max_length=8),
        ),
    ]
