# Generated by Django 5.1.2 on 2024-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_image_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='cars.color'),
        ),
    ]
