# Generated by Django 5.1.2 on 2024-11-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_found_at'),
        ('cars', '0006_alter_car_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brands.brand'),
        ),
    ]
