# Generated by Django 5.1.3 on 2024-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_price_alter_car_modelyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bodyType',
            field=models.CharField(choices=[('SUV', 'Suv'), ('SED', 'Sedan'), ('SPR', 'Sport'), ('PIK', 'Pick-up'), ('CON', 'Convertable'), ('COU', 'Coupe'), ('MIV', 'Minivan')], max_length=128),
        ),
    ]
