# Generated by Django 5.1.3 on 2024-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_photo_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='car_photos/'),
        ),
    ]
