# Generated by Django 5.1.3 on 2024-11-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_car_type_alter_car_colors_alter_car_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
