# Generated by Django 5.1.3 on 2024-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_rename_photo_color_photo_color_remove_color_hex_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="color", old_name="photo_color", new_name="photo",
        ),
        migrations.AddField(
            model_name="color",
            name="hex_code",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
