# Generated by Django 5.1.3 on 2024-11-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_bodytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bodyType',
            field=models.CharField(choices=[('SUV', 'Suv'), ('Sedan', 'Sedan'), ('Sport', 'Sport'), ('Pick-up', 'Pick-up'), ('Convertable', 'Convertable'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan')], max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Gasoline', 'Gasoline')], max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=128),
        ),
        migrations.AlterField(
            model_name='color',
            name='hexCode',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=258, unique=True),
        ),
    ]
