# Generated by Django 5.1.3 on 2024-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cargoSpace',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.TextField(default='Unknown', max_length=450),
        ),
        migrations.AlterField(
            model_name='car',
            name='infotainment',
            field=models.TextField(default='Basic', max_length=450),
        ),
        migrations.AlterField(
            model_name='car',
            name='performance',
            field=models.TextField(default='Standard', max_length=450),
        ),
    ]
