# Generated by Django 5.1.3 on 2024-11-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_cargospace_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='infotainment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='performance',
            field=models.TextField(default=''),
        ),
    ]
