# Generated by Django 5.1.3 on 2024-11-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_review_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
